# Generated by Django 5.1.1 on 2024-10-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_currency_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalcurrency',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
