# Generated by Django 5.1.1 on 2024-10-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_merchant', '0002_alter_historicalmerchant_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmerchant',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
