# Generated by Django 5.1.1 on 2024-10-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_merchant', '0003_alter_historicalmerchant_email_alter_merchant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmerchant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
