# Generated by Django 4.1.13 on 2024-08-28 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=None, help_text='Enter a valid Bangladeshi phone number.', max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid Bangladeshi phone number format. Use 01XXXXXXXXX, +8801XXXXXXXXX, or 008801XXXXXXXXX.', regex='^(01|(\\+8801)|008801)[3-9]\\d{8}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
