# Generated by Django 5.1 on 2024-09-16 04:44

import app_auth.models.agent_profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0003_agentprofile_back_side_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='nid_number',
            field=models.CharField(max_length=17, unique=True, validators=[app_auth.models.agent_profile.validate_nid_number]),
        ),
        migrations.AlterField(
            model_name='historicalagentprofile',
            name='nid_number',
            field=models.CharField(db_index=True, max_length=17, validators=[app_auth.models.agent_profile.validate_nid_number]),
        ),
    ]
