# Generated by Django 5.1 on 2024-09-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0004_alter_agentprofile_nid_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='new_user',
            field=models.BooleanField(default=True),
        ),
    ]
