# Generated by Django 5.1.1 on 2024-09-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0005_customuser_new_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='selfie_with_document',
            field=models.ImageField(null=True, upload_to='uploads/verification/selfie_with_document/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='historicalagentprofile',
            name='selfie_with_document',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='back_side_document',
            field=models.ImageField(null=True, upload_to='uploads/verification/back_side/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='front_side_document',
            field=models.ImageField(null=True, upload_to='uploads/verification/front_side/%Y/%m/%d'),
        ),
    ]
