# Generated by Django 5.1.1 on 2024-09-30 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0006_agentprofile_selfie_with_document_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalAgentProfile',
        ),
    ]
