# Generated by Django 5.1.1 on 2024-09-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0007_delete_historicalagentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='2024-01-01', max_length=255),
            preserve_default=False,
        ),
    ]
