# Generated by Django 5.1.1 on 2024-10-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0008_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
