# Generated by Django 5.1.1 on 2024-10-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0009_alter_agentprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
